version: "3"
services: 
  app:
    build: 
      context: .
    volumes: 
      - ./:/works/app
    ports: 
      - "28080:8080"
      - "28443:8443"
    command: /works/code-server --auth none --host 0.0.0.0 --port 8443 /app
    
