version: "3"
services: 
  app:
    build: 
      context: .
    volumes: 
      - ./:/works/app
    ports: 
      - "28080:8080"
      - "28443:8443"
    command: /works/code-server --no-auth --allow-http --port 8443 --host 0.0.0.0 

    
