version: '3'
services: 
  app:
    build: .
    ports: 
      - "8080:8080"
      - "8443:8443"
      - "5900:5900"
      - "5901:5901"
      - "5902:5902"
      - "5920:5920"
    #command: ["tail","-f","/dev/null"]
    privileged: true
    command: ["sh", "/root/execute.sh"]

