version: '3'
services: 
  web:
    build: .
    ports:
      - "8080:8080"
      - "8443:8443"
    links:
      - mysql
    command: /works/code-server /works --allow-http --no-auth
  mysql: 
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: hello
      MYSQL_USER: root
      MYSQL_PASSWORD: passwd


