version: '3'
services: 
  app:
    build: ./app
    volumes: 
      - ./app:/works/app
    ports:
      - "8080:8080"
      - "8443:8443"
    links:
      - mysqld
    command: /works/code-server /works --allow-http --no-auth --port 8443

  mysqld: 
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: hello
      MYSQL_USER: root
      MYSQL_PASSWORD: passwd

