version: '3'
services:
  base:
    build: .
    ports:
     - "8080:8080"
     - "8443:8443"
    volumes: 
     - /var/run/docker.sock:/var/run/docker.sock
    command: /works/code-server/code-server /works --allow-http --no-auth -p 8443

