# spring:
datasource:
  one:
    url: jdbc:mysql://mysqld:3306/user_db?autoReconnect=true&useSSL=false
    username: root
    password: passwd
    driverClassName: com.mysql.jdbc.Driver
  two:
    url: jdbc:mysql://mysqld:3306/app_db?autoReconnect=true&useSSL=false
    username: root
    password: passwd
    driverClassName: com.mysql.jdbc.Driver
